import os
from dotenv import load_dotenv
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL= os.getenv("GEMINI_MODEL")
GEMINI_ENDPOINT = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"
# Global prompt for extraction and comparison
GLOBAL_OCR_PROMPT = """
You are an advanced AI specializing in text extraction, data normalization, and structured data comparison.
Your task is to perform two operations:
1. Extract data from the provided ID card image. Extract the following fields:
   - Full Name
   - Date of Birth (DoB)
   - Nationality
   - ID Number
2. Compare the extracted data with the static form data provided below.
Static Form Data:
   • Full Name: {form_full_name}
   • Date of Birth: {form_dob}
   • Nationality: {form_nationality}
   • ID Number: {form_id_number}

Comparison Rules:
- Full Name: Use a fuzzy matching algorithm to allow minor typos.
- Date of Birth: Normalize various formats (e.g., MM/DD/YYYY, DD/MM/YYYY) and compare numeric values.
- Nationality: If the extracted nationality is missing or cannot be inferred, return it as NULL and exclude it from similarity scoring. Otherwise, compare it normally and include a similarity score.
- ID Number: Must match exactly and contain at least 9 characters (DO NOT INCLUDE THE SPACING IN CONSIDERATION WHEN COMPARING).

Output Format (JSON):
{{
  "status": "success | fail | flag",
  "Similarity Score : From 0 to 100 ",
  "message": "Comparison succeeded | Comparison failed | Partial match with issues",
  "detailed_result": {{
    "full_name": {{
      "form_value": "{form_full_name}",
      "extracted_value": "<value>",
      "match": true | false,
      "similarity_score": <0-100>
    }},
    "dob": {{
      "form_value": "{form_dob}",
      "extracted_value": "<value>",
      "match": true | false,
      "similarity_score": <0-100>
    }},
    "nationality": {{
      "form_value": "{form_nationality}",
      "extracted_value": "<value> | NULL",
      "match": true | false,
      "similarity_score": <0-100>
    }},
    "id_number": {{
      "form_value": "{form_id_number}",
      "extracted_value": "<value>",
      "match": true | false
    }}
  }},
  "ps": "Additional note if comparison failed"
}}

Generate only the structured JSON output with no extra explanation.
"""
# --------------------------------------------------------------------
# Global prompt for metadata analyze
GLOBAL_TAMPERING_PROMPT = """
You are a digital forensics expert specializing in EXIF metadata analysis. Your task is to analyze the complete metadata extracted from an image file and detect any signs of tampering or manipulation. Please perform the following checks:

1. Authenticity Checks:
   - Software: Identify any editing tools such as Photoshop, GIMP, Snapseed, etc.
   - Compression & Resolution: Check for anomalies in compression or resolution that might indicate re-saving or modification.

2. Consistency Checks:
   - Make & Model: Ensure that the camera's make and model are present and consistent.
   - ImageUniqueID: Verify the presence of this field; its absence may indicate editing.
   - ExifVersion: Confirm that this field exists as it should in genuine images.

3. Tampering Signs:
   - GPS Data: If available, analyze the GPS information for logical consistency.
   - Unusual Metadata Gaps: Note any missing key fields that could suggest manipulation.

If any required field is missing, do not automatically fail the analysis; instead, weigh the evidence and explain your reasoning.

Respond strictly in JSON format with no extra commentary using the following structure:

{{
  "status": "success" or "fail",
  "message": "<detailed explanation of the forensic analysis, noting any inconsistencies, tampering, or fraud indicators>"
}}

Complete Metadata:
{metadata}
"""
# --------------------------------------------------------------------
GLOBAL_DECISION_PROMPT = """
You are an elite AI engineered for rigorous data analysis and decisive judgment. You will receive a comprehensive dataset generated by our verification pipeline, comprising:
  - OCR Verification
  - Metadata Verification
  - Error Level Analysis (ELA)
  - Image Forensics Check

Each of these checks contributes exactly 25% to the overall evaluation. The dataset always includes a 'status' field along with other essential fields.

Your mission is to analyze the provided data and deliver one definitive decision: either "accept", "deny", or "flag for review". You MUST respond using the exact JSON structure below, with no additional commentary:

{{
  "decision": "<accept/deny/flag for review>",
  "reason": "<brief explanation of your decision>"
}}

Any output deviating from this structure is unacceptable. Process the data and return your decision accordingly.
"""
